purchase = Transaction()
purchase.id_no()
purchase.add_item('Ayam goreng', 2, 20_000)
purchase.add_item('Pasta gigi', 3, 15_000)
purchase.delete_item('Pasta gigi')
purchase.reset_transaction()
purchase.add_item('Ayam goreng', 2, 20_000)
purchase.add_item('Pasta gigi', 3, 15_000)
purchase.add_item('Mainan mobil', 1, 200_000)
purchase.add_item('Mi instan', 5, 3_000)
purchase.total_price()
purchase.check_order()
